# Generated by Django 4.1.2 on 2022-11-16 04:37

from django.db import migrations, models
import django.db.models.deletion
import transporte_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Combustibles",
            fields=[
                (
                    "name",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("precio", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "subelemento_gastos",
                    models.CharField(
                        max_length=5, validators=[transporte_app.models.only_digit]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vehiculo",
            fields=[
                (
                    "matricula",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("tipo", models.CharField(max_length=20)),
                ("marca", models.CharField(max_length=50)),
                ("modelo", models.CharField(max_length=50)),
                ("color", models.CharField(max_length=20)),
                ("indice_consumo_real", models.FloatField()),
                ("f_act_indice", models.DateField()),
                ("f_vencFICAV", models.DateField()),
                ("f_venc_lic_operativa", models.DateField()),
                ("estado_tec", models.BooleanField(default=True)),
                ("cap_tanque", models.PositiveIntegerField()),
                ("prueba_litro", models.DateField()),
                ("num_motor", models.CharField(max_length=20)),
                ("num_chasis", models.CharField(max_length=20)),
                ("num_AFT", models.IntegerField()),
                (
                    "combustible",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="t_combustible",
                        to="transporte_app.combustibles",
                    ),
                ),
            ],
        ),
    ]
