# Generated by Django 4.1.2 on 2022-11-16 06:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("transporte_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vehiculo",
            old_name="estado_tec",
            new_name="apto",
        ),
        migrations.CreateModel(
            name="MantenimientoAnual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mes",
                    models.IntegerField(
                        choices=[
                            (1, "Enero"),
                            (2, "Febrero"),
                            (3, "Marzo"),
                            (4, "Abril"),
                            (5, "Mayo"),
                            (6, "Junio"),
                            (7, "Julio"),
                            (8, "Agosto"),
                            (9, "Septiembre"),
                            (10, "Octubre"),
                            (11, "Noviembre"),
                            (12, "Diciembre"),
                        ]
                    ),
                ),
                (
                    "anno",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2020),
                            django.core.validators.MaxValueValidator(2100),
                        ]
                    ),
                ),
                ("plan_consumo", models.FloatField()),
                ("km_a_recorrer", models.FloatField()),
                ("km_prox_mant", models.FloatField(blank=True, null=True)),
                ("km_recorridos", models.FloatField(blank=True, null=True)),
                ("fecha_mant", models.CharField(blank=True, max_length=20)),
                (
                    "actividad",
                    models.CharField(
                        blank=True, default="Mantenimiento Anual", max_length=200
                    ),
                ),
                ("descripcion", models.CharField(blank=True, max_length=200)),
                (
                    "matricula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="t_matricula",
                        to="transporte_app.vehiculo",
                    ),
                ),
            ],
            options={
                "ordering": ["anno", "mes"],
                "unique_together": {("mes", "anno", "matricula")},
            },
        ),
    ]
