# Generated by Django 4.1.2 on 2022-11-18 04:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("transporte_app", "0002_rename_estado_tec_vehiculo_apto_mantenimientoanual"),
    ]

    operations = [
        migrations.CreateModel(
            name="Articulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Resolucion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name="vehiculo",
            name="prueba_litro",
            field=models.DateField(blank=True),
        ),
        migrations.CreateModel(
            name="Resultado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mes",
                    models.IntegerField(
                        choices=[
                            (1, "Enero"),
                            (2, "Febrero"),
                            (3, "Marzo"),
                            (4, "Abril"),
                            (5, "Mayo"),
                            (6, "Junio"),
                            (7, "Julio"),
                            (8, "Agosto"),
                            (9, "Septiembre"),
                            (10, "Octubre"),
                            (11, "Noviembre"),
                            (12, "Diciembre"),
                        ]
                    ),
                ),
                (
                    "anno",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2020),
                            django.core.validators.MaxValueValidator(2100),
                        ]
                    ),
                ),
                (
                    "respuesta",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "SI"), (0, "NO"), (-1, "NP")],
                        default="",
                    ),
                ),
                ("accion", models.CharField(blank=True, default="", max_length=200)),
                (
                    "articulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="t_articulo",
                        to="transporte_app.articulo",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="articulo",
            name="resolucion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="t_resolucion",
                to="transporte_app.resolucion",
            ),
        ),
    ]
