# Generated by Django 4.1.2 on 2022-11-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transporte_app", "0004_articulo_desc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articulo",
            name="desc",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="resultado",
            name="respuesta",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "SI"), (0, "NO"), (-1, "NP")],
                default=None,
                null=True,
            ),
        ),
    ]
