# Generated by Django 4.1.2 on 2022-11-19 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transporte_app", "0005_alter_articulo_desc_alter_resultado_respuesta"),
    ]

    operations = [
        migrations.RenameField(
            model_name="articulo",
            old_name="desc",
            new_name="descripcion",
        ),
        migrations.RenameField(
            model_name="articulo",
            old_name="name",
            new_name="nameArticulo",
        ),
        migrations.RenameField(
            model_name="resolucion",
            old_name="name",
            new_name="nameResolucion",
        ),
    ]
