# Generated by Django 4.1.2 on 2022-11-19 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transporte_app", "0007_alter_resultado_unique_together"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Resultado",
            new_name="Autocontrol",
        ),
    ]
