# Generated by Django 4.1.2 on 2022-11-20 04:29

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import transporte_app.models


class Migration(migrations.Migration):

    dependencies = [
        ("transporte_app", "0008_rename_resultado_autocontrol"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tarjetas",
            fields=[
                (
                    "numero",
                    models.CharField(
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                        validators=[transporte_app.models.only_digit],
                    ),
                ),
                ("c_control", models.CharField(blank=True, max_length=100)),
                ("fecha", models.DateField(default=datetime.date.today)),
                ("receptor", models.CharField(blank=True, max_length=100)),
                (
                    "ci",
                    models.CharField(
                        max_length=11, validators=[transporte_app.models.only_digit]
                    ),
                ),
                ("lit_inicio", models.FloatField()),
                ("chat_pr", models.FloatField()),
                ("activa", models.BooleanField(default=True)),
                (
                    "estado",
                    models.IntegerField(
                        choices=[
                            (1, "Asignada"),
                            (2, "Existencia"),
                            (3, "Vencida"),
                            (4, "Cancelada"),
                            (5, "Pérdida o Deterioro"),
                        ],
                        default=2,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="vehiculo",
            name="indice_consumo_fabricante",
            field=models.FloatField(default=9.8),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Tikets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField()),
                (
                    "matricula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="t_matricula_tiket",
                        to="transporte_app.vehiculo",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="vehiculo",
            name="tarjeta_asociada",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="t_tarjeta",
                to="transporte_app.tarjetas",
            ),
        ),
        migrations.CreateModel(
            name="EquipoEquipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mes",
                    models.IntegerField(
                        choices=[
                            (1, "Enero"),
                            (2, "Febrero"),
                            (3, "Marzo"),
                            (4, "Abril"),
                            (5, "Mayo"),
                            (6, "Junio"),
                            (7, "Julio"),
                            (8, "Agosto"),
                            (9, "Septiembre"),
                            (10, "Octubre"),
                            (11, "Noviembre"),
                            (12, "Diciembre"),
                        ]
                    ),
                ),
                (
                    "anno",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2020),
                            django.core.validators.MaxValueValidator(2100),
                        ]
                    ),
                ),
                ("indice_consumo_fabricante", models.FloatField()),
                ("actividad_real", models.FloatField()),
                ("comb_serviciado", models.PositiveIntegerField()),
                ("comb_inicio_mes", models.PositiveIntegerField()),
                ("comb_fin_mes", models.PositiveIntegerField()),
                ("comb_consumido", models.PositiveIntegerField()),
                ("comb_debio_consumir", models.FloatField()),
                ("indice_consumo_real", models.FloatField()),
                ("indice_comsumo_normado", models.FloatField()),
                ("Dif_consumo", models.FloatField()),
                ("desviacion_indice_normado", models.FloatField()),
                ("desviacion_absoluta", models.FloatField()),
                (
                    "combustible",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="t_combustible_ee",
                        to="transporte_app.combustibles",
                    ),
                ),
                (
                    "matricula_ee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="t_matricula_ee",
                        to="transporte_app.vehiculo",
                    ),
                ),
            ],
            options={
                "ordering": ["matricula_ee"],
                "unique_together": {("mes", "anno", "matricula_ee")},
            },
        ),
    ]
