# Generated by Django 4.1.2 on 2022-11-20 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "transporte_app",
            "0009_tarjetas_vehiculo_indice_consumo_fabricante_tikets_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiculo",
            name="tarjeta_asociada",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="t_tarjeta_asociada",
                to="transporte_app.tarjetas",
            ),
        ),
    ]
