# Generated by Django 4.1.2 on 2022-11-20 07:05

from django.db import migrations, models
import django.db.models.deletion
import transporte_app.models


class Migration(migrations.Migration):

    dependencies = [
        ("transporte_app", "0010_alter_vehiculo_tarjeta_asociada"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehiculo",
            name="chofer",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="tarjetas",
            name="chat_pr",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tarjetas",
            name="ci",
            field=models.CharField(
                blank=True, max_length=11, validators=[transporte_app.models.only_digit]
            ),
        ),
        migrations.AlterField(
            model_name="tarjetas",
            name="lit_inicio",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vehiculo",
            name="tarjeta_asociada",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="t_tarjeta_asociada_a",
                to="transporte_app.tarjetas",
            ),
        ),
    ]
