# Generated by Django 4.1.2 on 2022-11-22 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "transporte_app",
            "0012_tikets_cantidad_entrada_tikets_cantidad_saldo_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tikets",
            options={"ordering": ["fecha"]},
        ),
        migrations.AlterUniqueTogether(
            name="tikets",
            unique_together={("fecha", "matricula")},
        ),
    ]
