# Generated by Django 4.1.2 on 2022-11-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transporte_app", "0013_alter_tikets_options_alter_tikets_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="combustibles",
            name="precio",
            field=models.FloatField(),
        ),
    ]
