# Generated by Django 4.1.2 on 2022-11-23 21:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("transporte_app", "0014_alter_combustibles_precio"),
    ]

    operations = [
        migrations.RenameField(
            model_name="equipoequipo",
            old_name="Dif_consumo",
            new_name="dif_consumo",
        ),
        migrations.CreateModel(
            name="MantenimientoReal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mes",
                    models.IntegerField(
                        choices=[
                            (1, "Enero"),
                            (2, "Febrero"),
                            (3, "Marzo"),
                            (4, "Abril"),
                            (5, "Mayo"),
                            (6, "Junio"),
                            (7, "Julio"),
                            (8, "Agosto"),
                            (9, "Septiembre"),
                            (10, "Octubre"),
                            (11, "Noviembre"),
                            (12, "Diciembre"),
                        ]
                    ),
                ),
                (
                    "anno",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2020),
                            django.core.validators.MaxValueValidator(2100),
                        ]
                    ),
                ),
                ("real_consumo_combustibles", models.FloatField()),
                ("km_recorridos", models.FloatField()),
                (
                    "actividad_realizada",
                    models.CharField(
                        blank=True, default="Mantenimiento mensual", max_length=400
                    ),
                ),
                ("observaciones", models.CharField(blank=True, max_length=400)),
                (
                    "matricula_mr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="t_matricula_mr",
                        to="transporte_app.vehiculo",
                    ),
                ),
            ],
            options={
                "ordering": ["mes"],
                "unique_together": {("mes", "anno", "matricula_mr")},
            },
        ),
    ]
