# Generated by Django 4.1.2 on 2022-11-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transporte_app", "0016_tarjetasdudosas_equiposineficientes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tarjetas",
            old_name="chat_pr",
            new_name="cliente_pr",
        ),
        migrations.AddField(
            model_name="tarjetas",
            name="combos",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
